### PR TITLE
Trying to get Duktape 1.6 working

### PR DESCRIPTION
**Pull request by nicksrandall**
I took the unmerged PR by @marbemac and @pytlesk4 and tried to get the one failing error to pass. From what I can tell, the test is testing that we get a proper sytax error when trying to compile a function. I can verify that when I use other invalid syntax, the test passes but for some reason when we try to compile "foo" as a function, it panics with some really cryptic errors.

@olebedev I am really appreciative of you work here, is there anyway you could give me some guidance on how to get this issue fixed. I'm not very familiar with C-Go.

Thanks so much in advance!

### CODE REVIEW

**Comment by nicksrandall** [comment]
It's might be worth mentioning that duktape 2.0 has been recently released. As soon I can grok how duktape and C-go works, I'd like to put together a PR for implementing the latest release from duktape.

**Comment by pytlesk4** [comment]
I can make a pull request for 2.0 https://github.com/stoplightio/go-duktape/tree/v3

**Comment by olebedev** [comment]
Hi @nicksrandall, thank you for attempts to solve the issue. It would be good if we will have the last duktape's version under the hood. May I ask you @pytlesk4 to make a PR with duktape 2.0 right into [v3](https://github.com/olebedev/go-duktape/tree/v3) branch?

**Comment by pytlesk4** [comment]
Sure, will try to get to it today.

**Comment by pytlesk4** [comment]
https://github.com/olebedev/go-duktape/pull/42

Let me know if you have questions!

**Comment by olebedev** [comment]
Closed. See #42.

**Pull request closed without merging**
