### PR TITLE
Upgrade to duktape v2.3.0

### PR DESCRIPTION
**Pull request by fjl**
This should hopefully fix some of the build warnings.

### CODE REVIEW

**Comment by fjl** [comment]
Damn, looks like this fails on windows/amd64.

**Comment by fjl** [comment]
I'm also seeing random crashes on other platforms.

```text
[duktape] Warning!
setTimeout invokes callback after the context was destroyed.
2 + 3 = 5
SIGABRT: abort
PC=0x7fff6ea6fb86 m=5 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff6ea6fb86
stack: frame={sp:0x700004488c98, fp:0x0} stack=[0x7000044092b0,0x700004488eb0)
0000700004488b98:  0000000000000000  0000000000000000 
0000700004488ba8:  0000000000000000  0000000000000000 
0000700004488bb8:  0000000000000000  0000000000000000 
0000700004488bc8:  0000000000000000  0000000000000000 
0000700004488bd8:  0000000000000000  0000000000000000 
0000700004488be8:  0c0918a55e8e001a  0000000007b04620 
0000700004488bf8:  00000000043fae7d  0000700004488d20 
0000700004488c08:  00000000043fae39  0000700004488c30 
0000700004488c18:  00007fff6e9ce616  0000700004488cf0 
0000700004488c28:  000017e400000001  0000700004488d10 
0000700004488c38:  00007fff6e9fdf55  0000700004488c70 
0000700004488c48:  00007fff6eade807  0000000000000038 
0000700004488c58:  0000000007b04620  0c0918a55e8e001a 
0000700004488c68:  0000000004707b80  00007fffa09cf240 
0000700004488c78:  00007fffa09ceca0  00007fff6e9b848c 
0000700004488c88:  0000000000000000  0000700004488cd0 
0000700004488c98: <00007fff6eb25c50  0000700004489000 
0000700004488ca8:  0000700004488ce8  00000000043fae7d 
0000700004488cb8:  0000000000000000  0000700004488d20 
0000700004488cc8:  00000000043fae39  0000700004488d00 
0000700004488cd8:  00007fff6e9d91c9  0000700004488d20 
0000700004488ce8:  00000000ffffffdf  ffffffff01000003 
0000700004488cf8:  0000000007b04620  0000000001000003 
0000700004488d08:  0000000004197486  0000000008805e00 
0000700004488d18:  00000000041e3e09  7468677561636e75 
0000700004488d28:  6c61766e6927203a  746e756f63206469 
0000700004488d38:  00000000041d0027  0000000000000000 
0000700004488d48:  0000000000000000  0000000007b04620 
0000700004488d58:  f87e3fbd5486a4a3  f87e4fbd50ce2983 
0000700004488d68:  0000000008809600  0000000000000000 
0000700004488d78:  0000000008809600  0000000000000000 
0000700004488d88:  f87e3fbd509f8906  000000c000042b08 
```

```text
[duktape] Warning!
setTimeout invokes callback after the context was destroyed.
2 + 3 = 5
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x41a8e40]

runtime stack:
runtime.throw(0x428fe59, 0x2a)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/signal_unix.go:374 +0x2f2

goroutine 69 [syscall]:
runtime.cgocall(0x418d3c0, 0xc000043ec8, 0x90008200400516b)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc000043e98 sp=0xc000043e60 pc=0x4004b4e
github.com/olebedev/go-duktape._Cfunc_duk_push_global_stash(0x7301f90)
	_cgo_gotypes.go:2445 +0x41 fp=0xc000043ec8 sp=0xc000043e98 pc=0x4176901
github.com/olebedev/go-duktape.(*Context).PushGlobalStash.func1(0x7301f90)
	/Users/fjl/develop/eth/src/github.com/olebedev/go-duktape/api.go:1024 +0x56 fp=0xc000043f00 sp=0xc000043ec8 pc=0x4187416
github.com/olebedev/go-duktape.(*Context).PushGlobalStash(0xc00000e490)
	/Users/fjl/develop/eth/src/github.com/olebedev/go-duktape/api.go:1024 +0x34 fp=0xc000043f18 sp=0xc000043f00 pc=0x417e044
github.com/olebedev/go-duktape.(*Context).putTimer(0xc00000e490, 0x3ff0000000000000)
	/Users/fjl/develop/eth/src/github.com/olebedev/go-duktape/timers.go:130 +0x2f fp=0xc000043f50 sp=0xc000043f18 pc=0x416c4df
github.com/olebedev/go-duktape.setInterval.func1(0x3ff0000000000000, 0xc00000e490, 0x3ff0000000000000)
	/Users/fjl/develop/eth/src/github.com/olebedev/go-duktape/timers.go:92 +0xde fp=0xc000043fc8 sp=0xc000043f50 pc=0x4181fde
runtime.goexit()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000043fd0 sp=0xc000043fc8 pc=0x405c021
created by github.com/olebedev/go-duktape.setInterval
	/Users/fjl/develop/eth/src/github.com/olebedev/go-duktape/timers.go:77 +0xab

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000a6100, 0x428709e, 0x4, 0x4292090, 0x4076ef6)
	/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:879 +0x37a
testing.runTe
````

**Comment by yazzaoui** [comment]
any update on this issue?

**Comment by olebedev** [comment]
Closed in favor of #64.

**Pull request closed without merging**
