### PR TITLE
update duktape to 1.5.1

### PR DESCRIPTION
**Pull request by marbemac**
Just had to change the use of C.duk_debugger_attach, as it looks like it's not externalized in duktape 1.5.1.

### CODE REVIEW

**Comment by pytlesk4** [comment]
Any idea on when this will get merged? Or does something else need to happen?

**Comment by olebedev** [comment]
I will merge it as soon as i will check if it works. In nearest future. Thanks for the contribution guys.

**Comment by olebedev** [comment]
Hi @marbemac,

did you run the tests?

**Comment by pytlesk4** [comment]
@olebedev I ran the test, I couldn't get one of them to pass though so I commented it out.

https://github.com/stoplightio/go-duktape/blob/v2/api_test.go#L22-L26

I think something internally changed with duktape, not sure though.

**Comment by nicksrandall** [comment]
Any update on this?

**Comment by olebedev** [comment]
@nicksrandall, waiting for tests passed

**Comment by olebedev** [comment]
Closed. See #42.

**Pull request closed without merging**
